# Site settings
title: "I'll Acccept Anything"
email: your-email@domain.com
description: "This is a github pages site that accepts any* thing"
url: "http://illacceptanything.github.io" # the base hostname & protocol for your site
twitter_username: horse_ebooks
github_username:  illacceptanything

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
